/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NovaPalavraPasseRouteImport } from './routes/nova-palavra-passe'
import { Route as OfertasIndexRouteImport } from './routes/ofertas/index'
import { Route as OfertasIdRouteImport } from './routes/ofertas/$id'
import { Route as TrabalhadoresIndexRouteImport } from './routes/trabalhadores/index'
import { Route as AuthenticatedEmpresaIndexRouteImport } from './routes/_authenticated/empresa/index'
import { Route as AuthenticatedEmpresaCreditosRouteImport } from './routes/_authenticated/empresa/creditos'
import { Route as AuthenticatedEmpresaNovaOfertaRouteImport } from './routes/_authenticated/empresa/nova-oferta'
import { Route as AuthenticatedEmpresaProcurarRouteImport } from './routes/_authenticated/empresa/procurar'
import { Route as AuthenticatedEmpresaRegistoRouteImport } from './routes/_authenticated/empresa/registo'
import { Route as AuthenticatedTrabalhadorIndexRouteImport } from './routes/_authenticated/trabalhador/index'
import { Route as AuthenticatedTrabalhadorPerfilRouteImport } from './routes/_authenticated/trabalhador/perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPalavraPasseRoute = NovaPalavraPasseRouteImport.update({
  id: '/nova-palavra-passe',
  path: '/nova-palavra-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasIndexRoute = OfertasIndexRouteImport.update({
  id: '/ofertas/',
  path: '/ofertas/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasIdRoute = OfertasIdRouteImport.update({
  id: '/ofertas/$id',
  path: '/ofertas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalhadoresIndexRoute = TrabalhadoresIndexRouteImport.update({
  id: '/trabalhadores/',
  path: '/trabalhadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpresaIndexRoute =
  AuthenticatedEmpresaIndexRouteImport.update({
    id: '/empresa/',
    path: '/empresa/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaCreditosRoute =
  AuthenticatedEmpresaCreditosRouteImport.update({
    id: '/empresa/creditos',
    path: '/empresa/creditos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaNovaOfertaRoute =
  AuthenticatedEmpresaNovaOfertaRouteImport.update({
    id: '/empresa/nova-oferta',
    path: '/empresa/nova-oferta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaProcurarRoute =
  AuthenticatedEmpresaProcurarRouteImport.update({
    id: '/empresa/procurar',
    path: '/empresa/procurar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaRegistoRoute =
  AuthenticatedEmpresaRegistoRouteImport.update({
    id: '/empresa/registo',
    path: '/empresa/registo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrabalhadorIndexRoute =
  AuthenticatedTrabalhadorIndexRouteImport.update({
    id: '/trabalhador/',
    path: '/trabalhador/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrabalhadorPerfilRoute =
  AuthenticatedTrabalhadorPerfilRouteImport.update({
    id: '/trabalhador/perfil',
    path: '/trabalhador/perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nova-palavra-passe': typeof NovaPalavraPasseRoute
  '/ofertas/$id': typeof OfertasIdRoute
  '/ofertas/': typeof OfertasIndexRoute
  '/trabalhadores/': typeof TrabalhadoresIndexRoute
  '/empresa/creditos': typeof AuthenticatedEmpresaCreditosRoute
  '/empresa/nova-oferta': typeof AuthenticatedEmpresaNovaOfertaRoute
  '/empresa/procurar': typeof AuthenticatedEmpresaProcurarRoute
  '/empresa/registo': typeof AuthenticatedEmpresaRegistoRoute
  '/trabalhador/perfil': typeof AuthenticatedTrabalhadorPerfilRoute
  '/empresa/': typeof AuthenticatedEmpresaIndexRoute
  '/trabalhador/': typeof AuthenticatedTrabalhadorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nova-palavra-passe': typeof NovaPalavraPasseRoute
  '/ofertas/$id': typeof OfertasIdRoute
  '/ofertas': typeof OfertasIndexRoute
  '/trabalhadores': typeof TrabalhadoresIndexRoute
  '/empresa/creditos': typeof AuthenticatedEmpresaCreditosRoute
  '/empresa/nova-oferta': typeof AuthenticatedEmpresaNovaOfertaRoute
  '/empresa/procurar': typeof AuthenticatedEmpresaProcurarRoute
  '/empresa/registo': typeof AuthenticatedEmpresaRegistoRoute
  '/trabalhador/perfil': typeof AuthenticatedTrabalhadorPerfilRoute
  '/empresa': typeof AuthenticatedEmpresaIndexRoute
  '/trabalhador': typeof AuthenticatedTrabalhadorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/nova-palavra-passe': typeof NovaPalavraPasseRoute
  '/ofertas/$id': typeof OfertasIdRoute
  '/ofertas/': typeof OfertasIndexRoute
  '/trabalhadores/': typeof TrabalhadoresIndexRoute
  '/_authenticated/empresa/creditos': typeof AuthenticatedEmpresaCreditosRoute
  '/_authenticated/empresa/nova-oferta': typeof AuthenticatedEmpresaNovaOfertaRoute
  '/_authenticated/empresa/procurar': typeof AuthenticatedEmpresaProcurarRoute
  '/_authenticated/empresa/registo': typeof AuthenticatedEmpresaRegistoRoute
  '/_authenticated/trabalhador/perfil': typeof AuthenticatedTrabalhadorPerfilRoute
  '/_authenticated/empresa/': typeof AuthenticatedEmpresaIndexRoute
  '/_authenticated/trabalhador/': typeof AuthenticatedTrabalhadorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/nova-palavra-passe'
    | '/ofertas/$id'
    | '/ofertas/'
    | '/trabalhadores/'
    | '/empresa/creditos'
    | '/empresa/nova-oferta'
    | '/empresa/procurar'
    | '/empresa/registo'
    | '/trabalhador/perfil'
    | '/empresa/'
    | '/trabalhador/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/nova-palavra-passe'
    | '/ofertas/$id'
    | '/ofertas'
    | '/trabalhadores'
    | '/empresa/creditos'
    | '/empresa/nova-oferta'
    | '/empresa/procurar'
    | '/empresa/registo'
    | '/trabalhador/perfil'
    | '/empresa'
    | '/trabalhador'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/nova-palavra-passe'
    | '/ofertas/$id'
    | '/ofertas/'
    | '/trabalhadores/'
    | '/_authenticated/empresa/creditos'
    | '/_authenticated/empresa/nova-oferta'
    | '/_authenticated/empresa/procurar'
    | '/_authenticated/empresa/registo'
    | '/_authenticated/trabalhador/perfil'
    | '/_authenticated/empresa/'
    | '/_authenticated/trabalhador/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NovaPalavraPasseRoute: typeof NovaPalavraPasseRoute
  OfertasIdRoute: typeof OfertasIdRoute
  OfertasIndexRoute: typeof OfertasIndexRoute
  TrabalhadoresIndexRoute: typeof TrabalhadoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-palavra-passe': {
      id: '/nova-palavra-passe'
      path: '/nova-palavra-passe'
      fullPath: '/nova-palavra-passe'
      preLoaderRoute: typeof NovaPalavraPasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas/': {
      id: '/ofertas/'
      path: '/ofertas'
      fullPath: '/ofertas/'
      preLoaderRoute: typeof OfertasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas/$id': {
      id: '/ofertas/$id'
      path: '/ofertas/$id'
      fullPath: '/ofertas/$id'
      preLoaderRoute: typeof OfertasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhadores/': {
      id: '/trabalhadores/'
      path: '/trabalhadores'
      fullPath: '/trabalhadores/'
      preLoaderRoute: typeof TrabalhadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empresa/': {
      id: '/_authenticated/empresa/'
      path: '/empresa'
      fullPath: '/empresa/'
      preLoaderRoute: typeof AuthenticatedEmpresaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/creditos': {
      id: '/_authenticated/empresa/creditos'
      path: '/empresa/creditos'
      fullPath: '/empresa/creditos'
      preLoaderRoute: typeof AuthenticatedEmpresaCreditosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/nova-oferta': {
      id: '/_authenticated/empresa/nova-oferta'
      path: '/empresa/nova-oferta'
      fullPath: '/empresa/nova-oferta'
      preLoaderRoute: typeof AuthenticatedEmpresaNovaOfertaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/procurar': {
      id: '/_authenticated/empresa/procurar'
      path: '/empresa/procurar'
      fullPath: '/empresa/procurar'
      preLoaderRoute: typeof AuthenticatedEmpresaProcurarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/registo': {
      id: '/_authenticated/empresa/registo'
      path: '/empresa/registo'
      fullPath: '/empresa/registo'
      preLoaderRoute: typeof AuthenticatedEmpresaRegistoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trabalhador/': {
      id: '/_authenticated/trabalhador/'
      path: '/trabalhador'
      fullPath: '/trabalhador/'
      preLoaderRoute: typeof AuthenticatedTrabalhadorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trabalhador/perfil': {
      id: '/_authenticated/trabalhador/perfil'
      path: '/trabalhador/perfil'
      fullPath: '/trabalhador/perfil'
      preLoaderRoute: typeof AuthenticatedTrabalhadorPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEmpresaCreditosRoute: typeof AuthenticatedEmpresaCreditosRoute
  AuthenticatedEmpresaNovaOfertaRoute: typeof AuthenticatedEmpresaNovaOfertaRoute
  AuthenticatedEmpresaProcurarRoute: typeof AuthenticatedEmpresaProcurarRoute
  AuthenticatedEmpresaRegistoRoute: typeof AuthenticatedEmpresaRegistoRoute
  AuthenticatedTrabalhadorPerfilRoute: typeof AuthenticatedTrabalhadorPerfilRoute
  AuthenticatedEmpresaIndexRoute: typeof AuthenticatedEmpresaIndexRoute
  AuthenticatedTrabalhadorIndexRoute: typeof AuthenticatedTrabalhadorIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEmpresaCreditosRoute: AuthenticatedEmpresaCreditosRoute,
  AuthenticatedEmpresaNovaOfertaRoute: AuthenticatedEmpresaNovaOfertaRoute,
  AuthenticatedEmpresaProcurarRoute: AuthenticatedEmpresaProcurarRoute,
  AuthenticatedEmpresaRegistoRoute: AuthenticatedEmpresaRegistoRoute,
  AuthenticatedTrabalhadorPerfilRoute: AuthenticatedTrabalhadorPerfilRoute,
  AuthenticatedEmpresaIndexRoute: AuthenticatedEmpresaIndexRoute,
  AuthenticatedTrabalhadorIndexRoute: AuthenticatedTrabalhadorIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NovaPalavraPasseRoute: NovaPalavraPasseRoute,
  OfertasIdRoute: OfertasIdRoute,
  OfertasIndexRoute: OfertasIndexRoute,
  TrabalhadoresIndexRoute: TrabalhadoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
